[CmdletBinding()]
param(
    [switch]$Backup,
    [switch]$SkipModules,
    [switch]$Force
)

$ErrorActionPreference = "Stop"

# Configuration
$repoRoot = Split-Path -Parent $PSScriptRoot
$themeFile = Join-Path $repoRoot "themes\personal.omp.json"
$profileSampleFile = Join-Path $PSScriptRoot "Microsoft.PowerShell_profile.ps1"

Write-Host "==================================" -ForegroundColor Cyan
Write-Host "Oh-My-Posh Profile Deployment" -ForegroundColor Cyan
Write-Host "==================================" -ForegroundColor Cyan
Write-Host ""

# Check if Oh My Posh is installed
Write-Host "Checking Oh My Posh installation..." -ForegroundColor Yellow
if (-not (Get-Command oh-my-posh -ErrorAction SilentlyContinue)) {
    Write-Host "Oh My Posh not found!" -ForegroundColor Red
    Write-Host "Please install Oh My Posh first:" -ForegroundColor Yellow
    Write-Host "  winget install JanDeDobbeleer.OhMyPosh -s winget" -ForegroundColor White
    exit 1
} else {
    $ompVersion = oh-my-posh --version
    Write-Host "✓ Oh My Posh is installed (version: $ompVersion)" -ForegroundColor Green
}

# Check theme file exists
Write-Host "Checking theme file..." -ForegroundColor Yellow
if (-not (Test-Path $themeFile)) {
    Write-Host "✗ Theme file not found at: $themeFile" -ForegroundColor Red
    exit 1
} else {
    Write-Host "✓ Theme file found" -ForegroundColor Green
}

# Validate theme
Write-Host "Validating theme..." -ForegroundColor Yellow
try {
    $validateResult = oh-my-posh config validate --config $themeFile 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "✗ Theme validation failed!" -ForegroundColor Red
        Write-Host $validateResult -ForegroundColor Red
        exit 1
    }
    Write-Host "✓ Theme is valid" -ForegroundColor Green
} catch {
    Write-Host "✗ Error validating theme: $_" -ForegroundColor Red
    exit 1
}

# Check PowerShell profile location
Write-Host "`nPowerShell Profile: $PROFILE" -ForegroundColor Cyan

# Backup existing profile if requested or if Force is used
if (Test-Path $PROFILE) {
    if ($Backup -or $Force) {
        $backupPath = "$PROFILE.backup.$(Get-Date -Format 'yyyyMMdd-HHmmss').ps1"
        Write-Host "Backing up existing profile to: $backupPath" -ForegroundColor Yellow
        Copy-Item $PROFILE $backupPath
        Write-Host "✓ Backup created" -ForegroundColor Green
    } else {
        Write-Host "Profile already exists. Use -Backup to create a backup or -Force to overwrite" -ForegroundColor Yellow
        $continue = Read-Host "Continue and modify existing profile? (y/N)"
        if ($continue -ne 'y' -and $continue -ne 'Y') {
            Write-Host "Deployment cancelled" -ForegroundColor Yellow
            exit 0
        }
    }
}

# Create profile directory if it doesn't exist
$profileDir = Split-Path -Parent $PROFILE
if (-not (Test-Path $profileDir)) {
    Write-Host "Creating profile directory: $profileDir" -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    Write-Host "✓ Profile directory created" -ForegroundColor Green
}

# Install required modules unless skipped
if (-not $SkipModules) {
    Write-Host "`nChecking required modules..." -ForegroundColor Yellow
    
    # PSReadLine
    if (-not (Get-Module -ListAvailable -Name PSReadLine)) {
        Write-Host "Installing PSReadLine..." -ForegroundColor Yellow
        try {
            Install-Module -Name PSReadLine -Force -SkipPublisherCheck -Scope CurrentUser
            Write-Host "✓ PSReadLine installed" -ForegroundColor Green
        } catch {
            Write-Host "✗ Failed to install PSReadLine: $_" -ForegroundColor Red
        }
    } else {
        Write-Host "✓ PSReadLine already installed" -ForegroundColor Green
    }
}

# Generate profile content
Write-Host "`nConfiguring PowerShell profile..." -ForegroundColor Yellow

$profileContent = @"
# Oh My Posh Configuration
# Generated by deploy-profile.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

`$ompConfig = Join-Path `$HOME "oh-my-posh-config" "themes" "personal.omp.json"
if (Test-Path `$ompConfig) {
    oh-my-posh init pwsh --config `$ompConfig | Invoke-Expression
} else {
    Write-Host "Oh My Posh config not found at: `$ompConfig" -ForegroundColor Yellow
}

# PSReadLine Configuration
if (Get-Module -ListAvailable -Name PSReadLine) {
    Import-Module PSReadLine
    Set-PSReadLineOption -PredictionSource History
    Set-PSReadLineOption -PredictionViewStyle ListView
    Set-PSReadLineOption -EditMode Windows
    Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
    Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
    Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
}

# Custom Aliases
Set-Alias -Name ll -Value Get-ChildItem -ErrorAction SilentlyContinue

# Useful Functions
function which(`$command) {
    Get-Command -Name `$command -ErrorAction SilentlyContinue | 
        Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue
}

function touch(`$file) {
    "" | Out-File `$file -Encoding ASCII
}

function .. { Set-Location .. }
function ... { Set-Location ..\.. }
function .... { Set-Location ..\..\.. }

# Welcome message
Write-Host "PowerShell $($PSVersionTable.PSVersion) with Oh My Posh" -ForegroundColor Cyan
"@

# Write profile
if ($Force -or -not (Test-Path $PROFILE)) {
    $profileContent | Out-File -FilePath $PROFILE -Encoding UTF8
    Write-Host "✓ Profile created successfully" -ForegroundColor Green
} else {
    # Append if profile exists and we didn't force
    Write-Host "Adding Oh-My-Posh configuration to existing profile..." -ForegroundColor Yellow
    
    # Check if oh-my-posh is already configured
    $existingContent = Get-Content $PROFILE -Raw
    if ($existingContent -match "oh-my-posh init") {
        Write-Host "Oh-My-Posh configuration already exists in profile" -ForegroundColor Yellow
        $replace = Read-Host "Replace existing Oh-My-Posh configuration? (y/N)"
        if ($replace -eq 'y' -or $replace -eq 'Y') {
            # Remove old oh-my-posh configuration block more carefully
            $lines = Get-Content $PROFILE
            $filteredLines = @()
            $skipBlock = $false
            
            foreach ($line in $lines) {
                if ($line -match "# Oh My Posh Configuration") {
                    $skipBlock = $true
                    continue
                }
                if ($skipBlock -and ($line -match "oh-my-posh init" -or $line -match '\$ompConfig')) {
                    continue
                }
                if ($skipBlock -and $line -match '^\s*$') {
                    $skipBlock = $false
                    continue
                }
                if (-not $skipBlock) {
                    $filteredLines += $line
                }
            }
            
            $filteredLines | Out-File -FilePath "$PROFILE.tmp" -Encoding UTF8
            $profileContent | Out-File -FilePath "$PROFILE.tmp" -Append -Encoding UTF8
            Move-Item "$PROFILE.tmp" $PROFILE -Force
            Write-Host "✓ Profile updated" -ForegroundColor Green
        }
    } else {
        "`n# Oh My Posh Configuration" | Out-File -FilePath $PROFILE -Append -Encoding UTF8
        $profileContent | Out-File -FilePath $PROFILE -Append -Encoding UTF8
        Write-Host "✓ Oh-My-Posh configuration added to profile" -ForegroundColor Green
    }
}

# Test profile
Write-Host "`nTesting profile configuration..." -ForegroundColor Yellow
try {
    . $PROFILE
    Write-Host "✓ Profile loaded successfully!" -ForegroundColor Green
} catch {
    Write-Host "✗ Error loading profile: $_" -ForegroundColor Red
    Write-Host "Please check the profile manually: $PROFILE" -ForegroundColor Yellow
    exit 1
}

Write-Host "`n==================================" -ForegroundColor Cyan
Write-Host "Deployment Complete!" -ForegroundColor Green
Write-Host "==================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Install a Nerd Font if you haven't already:" -ForegroundColor White
Write-Host "   oh-my-posh font install" -ForegroundColor Gray
Write-Host "2. Configure your terminal to use the Nerd Font" -ForegroundColor White
Write-Host "3. Restart your terminal or run: . `$PROFILE" -ForegroundColor White
Write-Host ""
Write-Host "For VSCode setup instructions, see:" -ForegroundColor Yellow
Write-Host "  $repoRoot\docs\vscode-setup.md" -ForegroundColor Gray
Write-Host ""
